---
- name: Manage rhel services
  hosts: all
  become: true
  tasks:
    - name: Make sure that the service is {{ service_state }}
      ansible.builtin.service:
        name: "{{ service_name }}"
        state: "{{ service_state }}"
